// Web IDL
// https://heycam.github.io/webidl
// https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/html/HTMLLinkElement.idl


destinations (as)
https://github.com/whatwg/fetch/pull/547
https://github.com/whatwg/html/pull/2588

w3c/preload
https://github.com/w3c/preload/pull/91
