#!/bin/bash

git add dist/snuggsi.es
git commit -m":muscle: bump distribution for dist/snuggsi.es"

git add dist/snuggsi.js
git commit -m":muscle: bump distribution for dist/snuggsi.js"

git add dist/snuggsi.min.js
git commit -m":muscle: bump distribution for dist/snuggsi.min.js"

git add dist/snuggsi.min.js.gz
git commit -m":muscle: bump distribution for dist/snuggsi.min.js.gz"

git push origin master
