#!/bin/bash

cp dist/snuggsi.es ./snuggsi.js && git add ./snuggsi.js
git commit -m":muscle: bump distribution for ./snuggsi.es"

git add dist/snuggsi.es
git commit -m":muscle: bump distribution for dist/snuggsi.es"

git add dist/snuggsi.js
git commit -m":muscle: bump distribution for dist/snuggsi.js"

git add dist/snuggsi.min.js
git commit -m":muscle: bump distribution for dist/snuggsi.min.js"

git add dist/snuggsi.min.js.gz
git commit -m":muscle: bump distribution for dist/snuggsi.min.js.gz"

git push origin master

npm version patch

git push origin master
git push origin --tags

npm publish

