#!/bin/bash

git add dist/snuggsi.es
git commit -m":muscle: bump distribution for dist/snuggsi.es"

cp dist/snuggsi.es ./snuggsi.js && git add ./snuggsi.js
git commit -m":muscle: bump distribution for ./snuggsi.js"

git add dist/snuggsi.min.es
git commit -m":muscle: bump distribution for dist/snuggsi.min.es"

cp dist/snuggsi.min.es ./snuggsi.min.js && git add ./snuggsi.min.js
git commit -m":muscle: bump distribution for ./snuggsi.min.js"

git add dist/snuggsi.min.es.gz
git commit -m":muscle: bump distribution for dist/snuggsi.min.es.gz"

git add dist/snuggsi.min.es.br
git commit -m":muscle: bump distribution for dist/snuggsi.min.es.br"

git add dist/snuggsi.js
git commit -m":muscle: bump distribution for dist/snuggsi.js"

git add dist/snuggsi.min.js
git commit -m":muscle: bump distribution for dist/snuggsi.min.js"

git add dist/snuggsi.min.js.gz
git commit -m":muscle: bump distribution for dist/snuggsi.min.js.gz"

git add dist/snuggsi.min.js.br
git commit -m":muscle: bump distribution for dist/snuggsi.min.js.br"

git push origin master

npm version patch

git push origin master
git push origin --tags

npm publish

