#!/bin/bash

rm -rf ./public/examples/*
cp -f  ./snippets/browser-sync.es ./public
cp -f  ./index.html ./public/index.html
cp -fr ./examples ./public
cp -f  ./dist/snuggsi.es ./snuggsi.js
cp -f  ./dist/snuggsi.es ./public/index.es

