#!/bin/bash

OCTETS=$(
  curl -sI https://raw.githubusercontent.com/devpunks/snuggsi/master/dist/snuggsi.min.es.br | \
  grep 'Content-Length'                                                                     | \
  awk '{ print $2 }'                                                                        | \
  tr -dc '0-9'
) || exit 1

if [[ "$OCTETS" -gt 1500 ]]; then
  >&2 echo "snuggsi is over weight: current size is $OCTETS, maximum allowable is 1500"

  exit 1
fi

exit 0
